name: githooks
hooks:
  - name: 'hooks: pre_commit'
    src: './tools/pre-commit'
    dst: './.git/hooks/pre-commit'
  - name: 'hooks: post-commit'
    src: './tools/post-commit'
    dst: './.git/hooks/post-commit'